
import { Phrase } from './types';

export const level2: Phrase[] = [
  { id: 'l2-1', english: 'I want to go to...', arabic: 'بدي أروح على...', transliteration: 'Biddi aroh ala...', category: 'Directions', level: 2 },
  { id: 'l2-2', english: 'Where is the bathroom?', arabic: 'وين الحمام؟', transliteration: 'Wein el-hammam?', category: 'Directions', level: 2 },
  { id: 'l2-3', english: 'Straight', arabic: 'دغري', transliteration: 'Doghri', category: 'Directions', level: 2 },
  { id: 'l2-4', english: 'Right', arabic: 'يمين', transliteration: 'Yameen', category: 'Directions', level: 2 },
  { id: 'l2-5', english: 'Left', arabic: 'شمال', transliteration: 'Shmal', category: 'Directions', level: 2 },
  { id: 'l2-6', english: 'Stop here', arabic: 'وقف هون', transliteration: 'Waggif hon', category: 'Directions', level: 2 },
  { id: 'l2-7', english: 'Turn', arabic: 'لف', transliteration: 'Liff', category: 'Directions', level: 2 },
  { id: 'l2-8', english: 'Wait for me', arabic: 'استناني', transliteration: 'Istannani', category: 'Social', level: 2 },
  { id: 'l2-9', english: 'Check, please', arabic: 'الحساب لو سمحت', transliteration: 'Al-hisab law samahet', category: 'Market', level: 2 },
  { id: 'l2-10', english: 'I am hungry', arabic: 'أنا جوعان', transliteration: 'Ana jow’an', category: 'Food', level: 2 },
  { id: 'l2-11', english: 'I am thirsty', arabic: 'أنا عطشان', transliteration: 'Ana atshan', category: 'Food', level: 2 },
  { id: 'l2-12', english: 'Is there food?', arabic: 'في أكل؟', transliteration: 'Fi akel?', category: 'Food', level: 2 },
  { id: 'l2-13', english: 'Water', arabic: 'مي', transliteration: 'Mayye', category: 'Food', level: 2 },
  { id: 'l2-14', english: 'Bread', arabic: 'خبز', transliteration: 'Khubiz', category: 'Food', level: 2 },
  { id: 'l2-15', english: 'Salt', arabic: 'ملح', transliteration: 'Mileh', category: 'Food', level: 2 },
  { id: 'l2-16', english: 'Sugar', arabic: 'سكر', transliteration: 'Sukkar', category: 'Food', level: 2 },
  { id: 'l2-17', english: 'Tea', arabic: 'شاي', transliteration: 'Shay', category: 'Food', level: 2 },
  { id: 'l2-18', english: 'Coffee', arabic: 'قهوة', transliteration: 'Gahwe', category: 'Food', level: 2 },
  { id: 'l2-19', english: 'Milk', arabic: 'حليب', transliteration: 'Haleeb', category: 'Food', level: 2 },
  { id: 'l2-20', english: 'Delicious', arabic: 'زاكي', transliteration: 'Zaki', category: 'Food', level: 2 },
  { id: 'l2-21', english: 'Hot (Food)', arabic: 'سخن', transliteration: 'Sokhon', category: 'Food', level: 2 },
  { id: 'l2-22', english: 'Cold (Food)', arabic: 'بارد', transliteration: 'Bared', category: 'Food', level: 2 },
  { id: 'l2-23', english: 'I am full', arabic: 'شبعت', transliteration: 'Shiba’et', category: 'Food', level: 2 },
  { id: 'l2-24', english: 'Thank God', arabic: 'الحمد لله', transliteration: 'Al-hamdu lillah', category: 'Social', level: 2 },
  { id: 'l2-25', english: 'Let’s go', arabic: 'يلا بينا / يلا', transliteration: 'Yalla bina / Yalla', category: 'Social', level: 2 },
  { id: 'l2-26', english: 'I want a taxi', arabic: 'بدي تاكسي', transliteration: 'Biddi taxi', category: 'Directions', level: 2 },
  { id: 'l2-27', english: 'Near', arabic: 'قريب', transliteration: 'Gareeb', category: 'Directions', level: 2 },
  { id: 'l2-28', english: 'Far', arabic: 'بعيد', transliteration: 'Ba’eed', category: 'Directions', level: 2 },
  { id: 'l2-29', english: 'Here', arabic: 'هون', transliteration: 'Hon', category: 'Directions', level: 2 },
  { id: 'l2-30', english: 'There', arabic: 'هناك', transliteration: 'Hunaka', category: 'Directions', level: 2 },
  { id: 'l2-31', english: 'I am tired', arabic: 'تعبان', transliteration: 'Ta’ban', category: 'Social', level: 2 },
  { id: 'l2-32', english: 'I am sick', arabic: 'مريض', transliteration: 'Mareed', category: 'Social', level: 2 },
  { id: 'l2-33', english: 'I need help', arabic: 'بدي مساعدة', transliteration: 'Biddi musa’ada', category: 'Social', level: 2 },
  { id: 'l2-34', english: 'Open', arabic: 'فاتح', transliteration: 'Fateh', category: 'Market', level: 2 },
  { id: 'l2-35', english: 'Closed', arabic: 'مسكر', transliteration: 'Mssakkir', category: 'Market', level: 2 },
  { id: 'l2-36', english: 'Expensive', arabic: 'غالي', transliteration: 'Ghali', category: 'Market', level: 2 },
  { id: 'l2-37', english: 'Cheap', arabic: 'رخيص', transliteration: 'Rakhees', category: 'Market', level: 2 },
  { id: 'l2-38', english: 'Money', arabic: 'مصاري', transliteration: 'Masari', category: 'Market', level: 2 },
  { id: 'l2-39', english: 'One JD', arabic: 'ليرة', transliteration: 'Leera', category: 'Market', level: 2 },
  { id: 'l2-40', english: 'Change (Coins)', arabic: 'فراطة', transliteration: 'Frata', category: 'Market', level: 2 },
  { id: 'l2-41', english: 'What is this called?', arabic: 'شو اسمه هذا؟', transliteration: 'Shu ismo hada?', category: 'Market', level: 2 },
  { id: 'l2-42', english: 'I like this', arabic: 'عاجبني هذا', transliteration: 'Ajibni hada', category: 'Social', level: 2 },
  { id: 'l2-43', english: "I don't like this", arabic: 'مش عاجبني هذا', transliteration: 'Mish ajibni hada', category: 'Social', level: 2 },
  { id: 'l2-44', english: 'Give me the bill', arabic: 'أعطيني الحساب', transliteration: 'A\'teeni al-hisab', category: 'Food', level: 2 },
  { id: 'l2-45', english: 'Spicy?', arabic: 'حراق؟', transliteration: 'Harraag?', category: 'Food', level: 2 },
  { id: 'l2-46', english: 'No sugar', arabic: 'بدون سكر', transliteration: 'Bidoun sukkar', category: 'Food', level: 2 },
  { id: 'l2-47', english: 'With milk', arabic: 'مع حليب', transliteration: 'Ma\' haleeb', category: 'Food', level: 2 },
  { id: 'l2-48', english: 'Spoon', arabic: 'معلقة', transliteration: 'Ma\'laga', category: 'Food', level: 2 },
  { id: 'l2-49', english: 'Fork', arabic: 'شوكة', transliteration: 'Showka', category: 'Food', level: 2 },
  { id: 'l2-50', english: 'Knife', arabic: 'سكينة', transliteration: 'Sikkeena', category: 'Food', level: 2 },
  { id: 'l2-51', english: 'Plate', arabic: 'صحن', transliteration: 'Sahan', category: 'Food', level: 2 },
  { id: 'l2-52', english: 'Napkin', arabic: 'فاين', transliteration: 'Fine', category: 'Food', level: 2 },
  { id: 'l2-53', english: 'Glass of water', arabic: 'كاسة مي', transliteration: 'Kasat mayye', category: 'Food', level: 2 },
  { id: 'l2-54', english: 'Breakfast', arabic: 'فطور', transliteration: 'Futour', category: 'Food', level: 2 },
  { id: 'l2-55', english: 'Lunch', arabic: 'غدا', transliteration: 'Ghada', category: 'Food', level: 2 },
  { id: 'l2-56', english: 'Dinner', arabic: 'عشا', transliteration: 'Asha', category: 'Food', level: 2 },
  { id: 'l2-57', english: 'Restaurant', arabic: 'مطعم', transliteration: 'Mat\'am', category: 'Food', level: 2 },
  { id: 'l2-58', english: 'Cafe', arabic: 'كافيه / قهوة', transliteration: 'Cafe / Gahwa', category: 'Food', level: 2 },
  { id: 'l2-59', english: 'Market / Souq', arabic: 'سوق', transliteration: 'Soug', category: 'Market', level: 2 },
  { id: 'l2-60', english: 'Mall', arabic: 'مول', transliteration: 'Mall', category: 'Market', level: 2 },
  { id: 'l2-61', english: 'Clothes', arabic: 'أواعي', transliteration: 'Awai', category: 'Market', level: 2 },
  { id: 'l2-62', english: 'Shoes', arabic: 'كندرة', transliteration: 'Kundara', category: 'Market', level: 2 },
  { id: 'l2-63', english: 'Shirt', arabic: 'قميص', transliteration: 'Gamees', category: 'Market', level: 2 },
  { id: 'l2-64', english: 'Pants', arabic: 'بنطلون', transliteration: 'Bantaloun', category: 'Market', level: 2 },
  { id: 'l2-65', english: 'Big size', arabic: 'مقاس كبير', transliteration: 'Magas kbeer', category: 'Market', level: 2 },
  { id: 'l2-66', english: 'Small size', arabic: 'مقاس صغير', transliteration: 'Magas sgheer', category: 'Market', level: 2 },
  { id: 'l2-67', english: 'Medium', arabic: 'وسط', transliteration: 'Wasat', category: 'Market', level: 2 },
  { id: 'l2-68', english: 'Another color', arabic: 'لون ثاني', transliteration: 'Lown thani', category: 'Market', level: 2 },
  { id: 'l2-69', english: 'Red', arabic: 'أحمر', transliteration: 'Ahmar', category: 'Social', level: 2 },
  { id: 'l2-70', english: 'Blue', arabic: 'أزرق', transliteration: 'Azrag', category: 'Social', level: 2 },
  { id: 'l2-71', english: 'Black', arabic: 'أسود', transliteration: 'Aswad', category: 'Social', level: 2 },
  { id: 'l2-72', english: 'White', arabic: 'أبيض', transliteration: 'Abyad', category: 'Social', level: 2 },
  { id: 'l2-73', english: 'Green', arabic: 'أخضر', transliteration: 'Akhdar', category: 'Social', level: 2 },
  { id: 'l2-74', english: 'Yellow', arabic: 'أصفر', transliteration: 'Asfar', category: 'Social', level: 2 },
  { id: 'l2-75', english: 'Today morning', arabic: 'اليوم الصبح', transliteration: 'El-youm el-soboh', category: 'Social', level: 2 },
  { id: 'l2-76', english: 'Today evening', arabic: 'اليوم المساء', transliteration: 'El-youm el-masa', category: 'Social', level: 2 },
  { id: 'l2-77', english: 'Tonight', arabic: 'هاليلة', transliteration: 'Ha-leileh', category: 'Social', level: 2 },
  { id: 'l2-78', english: 'Next week', arabic: 'الأسبوع الجاي', transliteration: 'El-usbua el-jay', category: 'Social', level: 2 },
  { id: 'l2-79', english: 'Last week', arabic: 'الأسبوع الماضي', transliteration: 'El-usbua el-madi', category: 'Social', level: 2 },
  { id: 'l2-80', english: 'Month', arabic: 'شهر', transliteration: 'Shahr', category: 'Social', level: 2 },
  { id: 'l2-81', english: 'Year', arabic: 'سنة', transliteration: 'Saneh', category: 'Social', level: 2 },
  { id: 'l2-82', english: 'Hour', arabic: 'ساعة', transliteration: 'Saa\'a', category: 'Social', level: 2 },
  { id: 'l2-83', english: 'Half an hour', arabic: 'نص ساعة', transliteration: 'Noss saa\'a', category: 'Social', level: 2 },
  { id: 'l2-84', english: 'Quarter', arabic: 'ربع', transliteration: 'Ruba\'', category: 'Social', level: 2 },
  { id: 'l2-85', english: 'Office', arabic: 'مكتب', transliteration: 'Maktab', category: 'Social', level: 2 },
  { id: 'l2-86', english: 'Company', arabic: 'شركة', transliteration: 'Sharikah', category: 'Social', level: 2 },
  { id: 'l2-87', english: 'Meeting', arabic: 'اجتماع', transliteration: 'Ijtimah', category: 'Social', level: 2 },
  { id: 'l2-88', english: 'Boss', arabic: 'مدير', transliteration: 'Mudeer', category: 'Social', level: 2 },
  { id: 'l2-89', english: 'Employee', arabic: 'موظف', transliteration: 'Muwathaf', category: 'Social', level: 2 },
  { id: 'l2-90', english: 'My car', arabic: 'سيارتي', transliteration: 'Siyarti', category: 'Directions', level: 2 },
  { id: 'l2-91', english: 'Parking', arabic: 'موقف', transliteration: 'Mowgif', category: 'Directions', level: 2 },
  { id: 'l2-92', english: 'Traffic', arabic: 'أزمة', transliteration: 'Azmeh', category: 'Directions', level: 2 },
  { id: 'l2-93', english: 'Police', arabic: 'شرطة', transliteration: 'Shurta', category: 'Social', level: 2 },
  { id: 'l2-94', english: 'Hospital', arabic: 'مستشفى', transliteration: 'Mustashfa', category: 'Social', level: 2 },
  { id: 'l2-95', english: 'Pharmacy', arabic: 'صيدلية', transliteration: 'Saydaliyeh', category: 'Social', level: 2 },
  { id: 'l2-96', english: 'Medicine', arabic: 'دوا', transliteration: 'Dawa', category: 'Social', level: 2 },
  { id: 'l2-97', english: 'Pain', arabic: 'وجع', transliteration: 'Waja\'', category: 'Social', level: 2 },
  { id: 'l2-98', english: 'Headache', arabic: 'صداع / وجع راس', transliteration: 'Suda\' / Waja\' ras', category: 'Social', level: 2 },
  { id: 'l2-99', english: 'Temperature', arabic: 'حرارة', transliteration: 'Harara', category: 'Social', level: 2 },
  { id: 'l2-100', english: 'Appointment', arabic: 'موعد', transliteration: 'Mow\'ed', category: 'Social', level: 2 },
  { id: 'l2-101', english: 'Family', arabic: 'عيلة', transliteration: 'Ayleh', category: 'Social', level: 2 },
  { id: 'l2-102', english: 'My father', arabic: 'أبوي', transliteration: 'Abouy', category: 'Social', level: 2 },
  { id: 'l2-103', english: 'My mother', arabic: 'أمي', transliteration: 'Ommi', category: 'Social', level: 2 },
  { id: 'l2-104', english: 'My brother', arabic: 'أخوي', transliteration: 'Akhouy', category: 'Social', level: 2 },
  { id: 'l2-105', english: 'My sister', arabic: 'أختي', transliteration: 'Okhti', category: 'Social', level: 2 },
  { id: 'l2-106', english: 'My kids', arabic: 'أولادي', transliteration: 'Awladi', category: 'Social', level: 2 },
  { id: 'l2-107', english: 'House', arabic: 'بيت', transliteration: 'Beit', category: 'Directions', level: 2 },
  { id: 'l2-108', english: 'Apartment', arabic: 'شقة', transliteration: 'Shagga', category: 'Directions', level: 2 },
  { id: 'l2-109', english: 'Rent', arabic: 'أجار', transliteration: 'Ajar', category: 'Market', level: 2 },
  { id: 'l2-110', english: 'Key', arabic: 'مفتاح', transliteration: 'Miftah', category: 'Social', level: 2 },
  { id: 'l2-111', english: 'Phone', arabic: 'تلفون', transliteration: 'Televon', category: 'Social', level: 2 },
  { id: 'l2-112', english: 'Internet', arabic: 'نت', transliteration: 'Net', category: 'Social', level: 2 },
  { id: 'l2-113', english: 'Password', arabic: 'كلمة سر', transliteration: 'Kalimat sirr', category: 'Social', level: 2 },
  { id: 'l2-114', english: 'Battery', arabic: 'بطارية', transliteration: 'Battariyeh', category: 'Social', level: 2 },
  { id: 'l2-115', english: 'Charger', arabic: 'شاحن', transliteration: 'Shahen', category: 'Social', level: 2 },
  { id: 'l2-116', english: 'Computer', arabic: 'كمبيوتر', transliteration: 'Computer', category: 'Social', level: 2 },
  { id: 'l2-117', english: 'Working?', arabic: 'شغال؟', transliteration: 'Shagghal?', category: 'Social', level: 2 },
  { id: 'l2-118', english: 'Broken', arabic: 'خربان', transliteration: 'Kharban', category: 'Social', level: 2 },
  { id: 'l2-119', english: 'Fix it', arabic: 'صلحه', transliteration: 'Salliho', category: 'Social', level: 2 },
  { id: 'l2-120', english: 'Done', arabic: 'خلصت', transliteration: 'Khallast', category: 'Social', level: 2 },
];
