import { Phrase } from './types';

export const level4: Phrase[] = [
  { id: 'l4-1', english: 'I swear (Honest)', arabic: 'والله العظيم', transliteration: 'Wallah al-azeem', category: 'Idioms', level: 4 },
  { id: 'l4-2', english: 'Don’t worry', arabic: 'ما تاكل هم', transliteration: 'Ma takol hamm', category: 'Social', level: 4 },
  { id: 'l4-3', english: 'What’s wrong with you?', arabic: 'شو مالك؟', transliteration: 'Shu malak?', category: 'Social', level: 4 },
  { id: 'l4-4', english: 'It’s none of your business', arabic: 'ما دخلك', transliteration: 'Ma dakhalak', category: 'Social', level: 4 },
  { id: 'l4-5', english: 'I am bored', arabic: 'زهقان', transliteration: 'Zahgan', category: 'Social', level: 4 },
  { id: 'l4-6', english: 'Good luck', arabic: 'بالتوفيق', transliteration: 'Bil-tawfeeq', category: 'Social', level: 4 },
  { id: 'l4-7', english: 'May God protect you', arabic: 'الله يحميك', transliteration: 'Allah yihmeek', category: 'Social', level: 4 },
  { id: 'l4-8', english: 'Take care', arabic: 'دير بالك على حالك', transliteration: 'Deer balak ala halak', category: 'Social', level: 4 },
  { id: 'l4-9', english: 'By the way', arabic: 'على فكرة', transliteration: 'Ala fikra', category: 'Social', level: 4 },
  { id: 'l4-10', english: 'Actually', arabic: 'بصراحة', transliteration: 'Bi-saraha', category: 'Social', level: 4 },
  { id: 'l4-11', english: 'To be honest', arabic: 'عشان أكون صادق', transliteration: 'Ashan akon sadig', category: 'Social', level: 4 },
  { id: 'l4-12', english: 'In my opinion', arabic: 'برأيي', transliteration: 'Bi-ra’yi', category: 'Social', level: 4 },
  { id: 'l4-13', english: 'Are you serious?', arabic: 'بتحكي جد؟', transliteration: 'Bit-ihki jad?', category: 'Social', level: 4 },
  { id: 'l4-14', english: 'Stop it', arabic: 'خلص بكفي', transliteration: 'Khalas bikaffi', category: 'Social', level: 4 },
  { id: 'l4-15', english: 'Whatever you say', arabic: 'زي ما بدك', transliteration: 'Zay ma biddak', category: 'Social', level: 4 },
  { id: 'l4-16', english: 'I am looking for a job', arabic: 'بدوّر على شغل', transliteration: 'Badawwer ala shughul', category: 'Social', level: 4 },
  { id: 'l4-17', english: 'I have an interview today', arabic: 'عندي مقابلة اليوم', transliteration: 'Andi muqabala el-youm', category: 'Social', level: 4 },
  { id: 'l4-18', english: 'What is your experience?', arabic: 'شو خبرتك؟', transliteration: 'Shu khibrtak?', category: 'Social', level: 4 },
  { id: 'l4-19', english: 'I want a high salary', arabic: 'بدي راتب عالي', transliteration: 'Biddi ratib ali', category: 'Market', level: 4 },
  { id: 'l4-20', english: 'The economy is difficult', arabic: 'الوضع الاقتصادي صعب', transliteration: 'El-wad\' el-iqtisadi sa\'eb', category: 'Social', level: 4 },
  { id: 'l4-21', english: 'Prices are rising', arabic: 'الأسعار عم بتغلى', transliteration: 'Al-as\'ar am bitighla', category: 'Market', level: 4 },
  { id: 'l4-22', english: 'I need to save money', arabic: 'لازم أوفر مصاري', transliteration: 'Lazim awaffir masari', category: 'Market', level: 4 },
  { id: 'l4-23', english: 'It is a waste of time', arabic: 'هذا مضيعة للوقت', transliteration: 'Hada madyah lil-waqt', category: 'Social', level: 4 },
  { id: 'l4-24', english: 'Don’t complicate things', arabic: 'لا تعقد الأمور', transliteration: 'La ta\'aggid al-umour', category: 'Social', level: 4 },
  { id: 'l4-25', english: 'Take it easy', arabic: 'خذ الأمور ببساطة', transliteration: 'Khod al-umour bi-basata', category: 'Social', level: 4 },
  { id: 'l4-26', english: 'Everything happens for a reason', arabic: 'كل شي بصير لسبب', transliteration: 'Kull shi biseer la-sabab', category: 'Idioms', level: 4 },
  { id: 'l4-27', english: 'It is written (Destiny)', arabic: 'هذا نصيب', transliteration: 'Hada naseeb', category: 'Idioms', level: 4 },
  { id: 'l4-28', english: 'God will provide', arabic: 'الله بفرجيها', transliteration: 'Allah bifarjeeha', category: 'Social', level: 4 },
  { id: 'l4-29', english: 'I am very optimistic', arabic: 'أنا كتير متفائل', transliteration: 'Ana kteer mutafa\'il', category: 'Social', level: 4 },
  { id: 'l4-30', english: 'Don’t be pessimistic', arabic: 'لا تكون متشائم', transliteration: 'La tkon mutasha\'im', category: 'Social', level: 4 },
  { id: 'l4-31', english: 'You surprised me', arabic: 'فاجأتني', transliteration: 'Faja\'tni', category: 'Social', level: 4 },
  { id: 'l4-32', english: 'It was a nice surprise', arabic: 'كانت مفاجأة حلوة', transliteration: 'Kanat mufaja\'a helwa', category: 'Social', level: 4 },
  { id: 'l4-33', english: 'I will think about it', arabic: 'راح أفكر بالموضوع', transliteration: 'Rah afakkir bil-mawdo\'', category: 'Social', level: 4 },
  { id: 'l4-34', english: 'I will give you an answer later', arabic: 'بعطيك جواب بعدين', transliteration: 'Ba\'teek jawab ba\'dein', category: 'Social', level: 4 },
  { id: 'l4-35', english: 'Do you have a better idea?', arabic: 'عندك فكرة أحسن؟', transliteration: 'Andak fikra ahsan?', category: 'Social', level: 4 },
  { id: 'l4-36', english: 'Let’s look at the options', arabic: 'خلينا نشوف الخيارات', transliteration: 'Khaleena nshouf al-khiyarat', category: 'Social', level: 4 },
  { id: 'l4-37', english: 'This is the best solution', arabic: 'هذا أحسن حل', transliteration: 'Hada ahsan hall', category: 'Social', level: 4 },
  { id: 'l4-38', english: 'I am against this idea', arabic: 'أنا ضد هي الفكرة', transliteration: 'Ana didd hai el-fikra', category: 'Social', level: 4 },
  { id: 'l4-39', english: 'I support you', arabic: 'أنا بدعمك', transliteration: 'Ana bad\'amak', category: 'Social', level: 4 },
  { id: 'l4-40', english: 'You have my support', arabic: 'دعمي معك', transliteration: 'Da\'mi ma\'ak', category: 'Social', level: 4 },
  { id: 'l4-41', english: 'Don’t let me down', arabic: 'لا تخذلني', transliteration: 'La takhthulni', category: 'Social', level: 4 },
  { id: 'l4-42', english: 'I rely on you', arabic: 'معتمد عليك', transliteration: 'Mu\'tamid aleik', category: 'Social', level: 4 },
  { id: 'l4-43', english: 'It is a huge responsibility', arabic: 'هي مسؤولية كبيرة', transliteration: 'Hai mas\'ouliyeh kbeera', category: 'Social', level: 4 },
  { id: 'l4-44', english: 'I will do my best', arabic: 'راح أعمل جهدي', transliteration: 'Rah a\'mal juhdi', category: 'Social', level: 4 },
  { id: 'l4-45', english: 'The project is successful', arabic: 'المشروع ناجح', transliteration: 'Al-mashrou\' najeh', category: 'Social', level: 4 },
  { id: 'l4-46', english: 'We need to cooperate', arabic: 'لازم نتعاون', transliteration: 'Lazim nit\'awan', category: 'Social', level: 4 },
  { id: 'l4-47', english: 'Unity is strength', arabic: 'في الاتحاد قوة', transliteration: 'Fil ittihad quwwa', category: 'Idioms', level: 4 },
  { id: 'l4-48', english: 'Don’t interfere in my life', arabic: 'لا تتدخل بحياتي', transliteration: 'La titdakhal bi-hayati', category: 'Social', level: 4 },
  { id: 'l4-49', english: 'Respect my privacy', arabic: 'احترم خصوصيتي', transliteration: 'Ihtarim khousousiyati', category: 'Social', level: 4 },
  { id: 'l4-50', english: 'I appreciate your help', arabic: 'بقدر مساعدتك', transliteration: 'Bagaddir musa\'adatak', category: 'Social', level: 4 },
  { id: 'l4-51', english: 'I am grateful to you', arabic: 'أنا ممتن إلك', transliteration: 'Ana mumtann ilak', category: 'Social', level: 4 },
  { id: 'l4-52', english: 'No thanks needed (Duty)', arabic: 'لا شكر على واجب', transliteration: 'La shukr ala wajib', category: 'Social', level: 4 },
  { id: 'l4-53', english: 'It is my pleasure', arabic: 'بكل سرور', transliteration: 'Bi-kull surour', category: 'Social', level: 4 },
  { id: 'l4-54', english: 'Are you available now?', arabic: 'إنت فاضي هسا؟', transliteration: 'Inta fadi hassa?', category: 'Social', level: 4 },
  { id: 'l4-55', english: 'I am in a hurry', arabic: 'أنا مستعجل', transliteration: 'Ana musta\'jil', category: 'Social', level: 4 },
  { id: 'l4-56', english: 'Take your time', arabic: 'خذ وقتك', transliteration: 'Khod waqtak', category: 'Social', level: 4 },
  { id: 'l4-57', english: 'The time has come', arabic: 'إجا الوقت', transliteration: 'Ija el-waqt', category: 'Social', level: 4 },
  { id: 'l4-58', english: 'Don’t delay it', arabic: 'لا تأجل الموضوع', transliteration: 'La ta\'ajjil el-mawdo\'', category: 'Social', level: 4 },
  { id: 'l4-59', english: 'Procrastination is bad', arabic: 'التأجيل مش منيح', transliteration: 'At-ta\'jeel mish mneeha', category: 'Social', level: 4 },
  { id: 'l4-60', english: 'I am very disappointed', arabic: 'أنا كتير خايب أملي', transliteration: 'Ana kteer khayib amali', category: 'Social', level: 4 },
  { id: 'l4-61', english: 'Don’t lose hope', arabic: 'لا تفقد الأمل', transliteration: 'La tifgid al-amal', category: 'Social', level: 4 },
  { id: 'l4-62', english: 'Hope is always there', arabic: 'الأمل دايما موجود', transliteration: 'Al-amal dayman mowjood', category: 'Social', level: 4 },
  { id: 'l4-63', english: 'I have a plan', arabic: 'عندي خطة', transliteration: 'Andi khutta', category: 'Social', level: 4 },
  { id: 'l4-64', english: 'Follow the instructions', arabic: 'اتبع التعليمات', transliteration: 'Itba\' at-ta\'leemat', category: 'Social', level: 4 },
  { id: 'l4-65', english: 'It is illegal', arabic: 'هذا غير قانوني', transliteration: 'Hada gheir qanouni', category: 'Social', level: 4 },
  { id: 'l4-66', english: 'I want to avoid problems', arabic: 'بدي أتجنب المشاكل', transliteration: 'Biddi at-jannab al-mashakil', category: 'Social', level: 4 },
  { id: 'l4-67', english: 'Peace of mind', arabic: 'راحة بال', transliteration: 'Rahat bal', category: 'Idioms', level: 4 },
  { id: 'l4-68', english: 'I am looking for peace', arabic: 'بدوّر على الهدوء', transliteration: 'Badawwer ala al-hudoo\'', category: 'Social', level: 4 },
  { id: 'l4-69', english: 'The place is crowded', arabic: 'المكان كتير عجقة', transliteration: 'Al-makan kteer ajga', category: 'Directions', level: 4 },
  { id: 'l4-70', english: 'I hate waiting', arabic: 'بكره الانتظار', transliteration: 'Bakrah al-intithar', category: 'Social', level: 4 },
  { id: 'l4-71', english: 'Patience is a key', arabic: 'الصبر مفتاح', transliteration: 'As-sabru miftah', category: 'Idioms', level: 4 },
  { id: 'l4-72', english: 'I am very proud', arabic: 'أنا كتير فخور', transliteration: 'Ana kteer fakhour', category: 'Social', level: 4 },
  { id: 'l4-73', english: 'Success takes effort', arabic: 'النجاح بده تعب', transliteration: 'An-najah biddah ta\'ab', category: 'Social', level: 4 },
  { id: 'l4-74', english: 'I am exhausted', arabic: 'أنا هلكان', transliteration: 'Ana halkan', category: 'Social', level: 4 },
  { id: 'l4-75', english: 'I need a vacation', arabic: 'بدي إجازة', transliteration: 'Biddi ijaza', category: 'Social', level: 4 },
  { id: 'l4-76', english: 'Where should we travel?', arabic: 'وين لازم نسافر؟', transliteration: 'Wein lazim n-safir?', category: 'Social', level: 4 },
  { id: 'l4-77', english: 'Exploring new places', arabic: 'استكشاف أماكن جديدة', transliteration: 'Istikshaf amakin jdeeda', category: 'Social', level: 4 },
  { id: 'l4-78', english: 'Life is short', arabic: 'العمر قصير', transliteration: 'Al-omr qaseer', category: 'Idioms', level: 4 },
  { id: 'l4-79', english: 'Enjoy every moment', arabic: 'استمتع بكل لحظة', transliteration: 'Istamta\' bi-kull lahtha', category: 'Social', level: 4 },
  { id: 'l4-80', english: 'Don’t look back', arabic: 'لا تطلع لوره', transliteration: 'La titalla\' la-wara', category: 'Social', level: 4 },
  { id: 'l4-81', english: 'Focus on the future', arabic: 'ركز على المستقبل', transliteration: 'Rakkiz ala al-mustaqbal', category: 'Social', level: 4 },
  { id: 'l4-82', english: 'I have many goals', arabic: 'عندي أهداف كتير', transliteration: 'Andi ahdaf kteer', category: 'Social', level: 4 },
  { id: 'l4-83', english: 'Dreams come true', arabic: 'الأحلام بتتحقق', transliteration: 'Al-ahlam bit-tahaqqaq', category: 'Social', level: 4 },
  { id: 'l4-84', english: 'Working hard', arabic: 'شغل بجد', transliteration: 'Shughul bi-jad', category: 'Social', level: 4 },
  { id: 'l4-85', english: 'I am very satisfied', arabic: 'أنا كتير راضي', transliteration: 'Ana kteer radi', category: 'Social', level: 4 },
  { id: 'l4-86', english: 'Is this possible?', arabic: 'هل هذا ممكن؟', transliteration: 'Hal hada mumkin?', category: 'Social', level: 4 },
  { id: 'l4-87', english: 'Under certain conditions', arabic: 'تحت شروط معينة', transliteration: 'Tahet shurout mu\'ayyana', category: 'Social', level: 4 },
  { id: 'l4-88', english: 'The contract is clear', arabic: 'العقد واضح', transliteration: 'Al-aqd wadah', category: 'Market', level: 4 },
  { id: 'l4-89', english: 'Sign here', arabic: 'وقع هون', transliteration: 'Waggi\' hon', category: 'Market', level: 4 },
  { id: 'l4-90', english: 'I read the terms', arabic: 'قرأت الشروط', transliteration: 'Gara\'t ash-shurout', category: 'Market', level: 4 },
  { id: 'l4-91', english: 'It is a fair deal', arabic: 'صفقة عادلة', transliteration: 'Safqa adila', category: 'Market', level: 4 },
  { id: 'l4-92', english: 'Bargaining is common', arabic: 'المفاصلة شي عادي', transliteration: 'Al-mufasala shi adi', category: 'Market', level: 4 },
  { id: 'l4-93', english: 'Don’t overcharge me', arabic: 'لا تغلي علي', transliteration: 'La tighli alay', category: 'Market', level: 4 },
  { id: 'l4-94', english: 'The price is fixed', arabic: 'السعر نهائي', transliteration: 'As-si\'er niha\'i', category: 'Market', level: 4 },
  { id: 'l4-95', english: 'I found a better price', arabic: 'لقيت سعر أحسن', transliteration: 'Lageit si\'er ahsan', category: 'Market', level: 4 },
  { id: 'l4-96', english: 'The market is volatile', arabic: 'السوق متقلب', transliteration: 'As-soug mutagallib', category: 'Market', level: 4 },
  { id: 'l4-97', english: 'Investing is risky', arabic: 'الاستثمار فيه مخاطرة', transliteration: 'Al-istithmar feeh mukhatara', category: 'Market', level: 4 },
  { id: 'l4-98', english: 'I trust my intuition', arabic: 'بثق بإحساسي', transliteration: 'Bathig bi-ihsasi', category: 'Social', level: 4 },
  { id: 'l4-99', english: 'Follow your heart', arabic: 'الحق قلبك', transliteration: 'Ilhag galbak', category: 'Idioms', level: 4 },
  { id: 'l4-100', english: 'Listen to your mind', arabic: 'اسمع لعقلك', transliteration: 'Isma\' la-aglak', category: 'Idioms', level: 4 },
  { id: 'l4-101', english: 'Conflict of interest', arabic: 'تضارب مصالح', transliteration: 'Tadarub masalih', category: 'Social', level: 4 },
  { id: 'l4-102', english: 'I am neutral', arabic: 'أنا محايد', transliteration: 'Ana muhayid', category: 'Social', level: 4 },
  { id: 'l4-103', english: 'No comment', arabic: 'لا تعليق', transliteration: 'La ta\'leeq', category: 'Social', level: 4 },
  { id: 'l4-104', english: 'The news is true', arabic: 'الخبر صحيح', transliteration: 'Al-khabar saheeh', category: 'Social', level: 4 },
  { id: 'l4-105', english: 'It is a rumor', arabic: 'هي إشاعة', transliteration: 'Hai isha\'a', category: 'Social', level: 4 },
  { id: 'l4-106', english: 'Don’t believe everything', arabic: 'لا تصدق كل شي', transliteration: 'La t-saddig kull shi', category: 'Social', level: 4 },
  { id: 'l4-107', english: 'The source is reliable', arabic: 'المصدر موثوق', transliteration: 'Al-masdar mowthoug', category: 'Social', level: 4 },
  { id: 'l4-108', english: 'Confirm the information', arabic: 'أكد المعلومة', transliteration: 'Akkid al-ma\'louma', category: 'Social', level: 4 },
  { id: 'l4-109', english: 'I am confused now', arabic: 'أنا متلخبط هسا', transliteration: 'Ana mut-lakhbat hassa', category: 'Social', level: 4 },
  { id: 'l4-110', english: 'Wait for the results', arabic: 'استنى النتائج', transliteration: 'Istanna an-nata\'ij', category: 'Social', level: 4 },
  { id: 'l4-111', english: 'It was a total failure', arabic: 'كان فشل ذريع', transliteration: 'Kan fashal tharee\'', category: 'Social', level: 4 },
  { id: 'l4-112', english: 'Learn from mistakes', arabic: 'تعلم من الأغلاط', transliteration: 'Ta\'allam min al-aghlat', category: 'Social', level: 4 },
  { id: 'l4-113', english: 'Next time will be better', arabic: 'المرة الجاية أحسن', transliteration: 'Al-marra el-jayeh ahsan', category: 'Social', level: 4 },
  { id: 'l4-114', english: 'I have high expectations', arabic: 'توقعاتي عالية', transliteration: 'Tawaqqu\'ati alyeh', category: 'Social', level: 4 },
  { id: 'l4-115', english: 'Don’t raise your hopes', arabic: 'لا ترفع سقف طموحاتك', transliteration: 'La tarfa\' saqf tumouhatak', category: 'Social', level: 4 },
  { id: 'l4-116', english: 'Be realistic', arabic: 'خليك واقعي', transliteration: 'Khalleek waqi\'i', category: 'Social', level: 4 },
  { id: 'l4-117', english: 'Imagination is wild', arabic: 'الخيال واسع', transliteration: 'Al-khayal wasi\'', category: 'Social', level: 4 },
  { id: 'l4-118', english: 'Creativity is important', arabic: 'الإبداع مهم', transliteration: 'Al-ibda\' muhem', category: 'Social', level: 4 },
  { id: 'l4-119', english: 'New perspectives', arabic: 'وجهات نظر جديدة', transliteration: 'Wijhat nathar jdeeda', category: 'Social', level: 4 },
  { id: 'l4-120', english: 'The world is changing', arabic: 'العالم عم يتغير', transliteration: 'Al-alam am yit-ghayyar', category: 'Social', level: 4 },
];
