import { Phrase } from './types';

export const level5: Phrase[] = [
  { id: 'l5-1', english: 'Long time no see', arabic: 'زمان عنك', transliteration: 'Zaman annak', category: 'Greetings', level: 5 },
  { id: 'l5-2', english: 'God give you health', arabic: 'الله يعطيك العافية', transliteration: 'Allah ya’teek al-afye', category: 'Greetings', level: 5 },
  { id: 'l5-3', english: 'It’s a piece of cake', arabic: 'شربة مي', transliteration: 'Shorbat mayye', category: 'Idioms', level: 5 },
  { id: 'l5-4', english: 'You are a legend', arabic: 'وحش', transliteration: 'Wahesh', category: 'Slang', level: 5 },
  { id: 'l5-5', english: 'Leave me alone', arabic: 'حل عني', transliteration: 'Hill anni', category: 'Slang', level: 5 },
  { id: 'l5-6', english: 'Don’t bother me', arabic: 'لا توجع راسي', transliteration: 'La tawja’ rasi', category: 'Slang', level: 5 },
  { id: 'l5-7', english: 'Keep it a secret', arabic: 'خليها بيناتنا', transliteration: 'Khaleeha beinatna', category: 'Social', level: 5 },
  { id: 'l5-8', english: 'On my head (Respect)', arabic: 'على راسي', transliteration: 'Ala rasi', category: 'Idioms', level: 5 },
  { id: 'l5-9', english: 'Bless you (after eating)', arabic: 'صحتين وعافية', transliteration: 'Sahtein wa afyeh', category: 'Food', level: 5 },
  { id: 'l5-10', english: 'Same to you (response)', arabic: 'على قلبك', transliteration: 'Ala galbak', category: 'Food', level: 5 },
  { id: 'l5-11', english: 'Mind your own business', arabic: 'خليك بحالك', transliteration: 'Khalleek bi-halak', category: 'Social', level: 5 },
  { id: 'l5-12', english: 'Don’t play with me', arabic: 'لا تلعب معي', transliteration: 'La til\'ab ma\'i', category: 'Social', level: 5 },
  { id: 'l5-13', english: 'Are you mocking me?', arabic: 'بتتمسخر علي؟', transliteration: 'Bit-timaskhar alay?', category: 'Social', level: 5 },
  { id: 'l5-14', english: 'He talks nonsense', arabic: 'هبّاد', transliteration: 'Habbad', category: 'Slang', level: 5 },
  { id: 'l5-15', english: 'It is a disaster', arabic: 'مصيبة', transliteration: 'Museeba', category: 'Social', level: 5 },
  { id: 'l5-16', english: 'God help us', arabic: 'الله يعين', transliteration: 'Allah ya\'een', category: 'Social', level: 5 },
  { id: 'l5-17', english: 'I am broke', arabic: 'مطفر', transliteration: 'Mutaffir', category: 'Slang', level: 5 },
  { id: 'l5-18', english: 'That is it for today', arabic: 'لهون وبس', transliteration: 'La-hon wa bas', category: 'Social', level: 5 },
  { id: 'l5-19', english: 'I am done with you', arabic: 'خلصت معك', transliteration: 'Khallast ma\'ak', category: 'Social', level: 5 },
  { id: 'l5-20', english: 'You are like a brother', arabic: 'إنت زي أخوي', transliteration: 'Inta zay akhouy', category: 'Social', level: 5 },
  { id: 'l5-21', english: 'Don’t be shy', arabic: 'لا تستحي', transliteration: 'La tistahi', category: 'Social', level: 5 },
  { id: 'l5-22', english: 'Our house is yours', arabic: 'البيت بيتك', transliteration: 'Al-beit beitak', category: 'Social', level: 5 },
  { id: 'l5-23', english: 'He is a noble man', arabic: 'زلمة غانم', transliteration: 'Zalameh ghanem', category: 'Social', level: 5 },
  { id: 'l5-24', english: 'May your hands be safe', arabic: 'يسلموا إيديك', transliteration: 'Yislamou ideik', category: 'Social', level: 5 },
  { id: 'l5-25', english: 'God increase your bounty', arabic: 'كثر الله خيرك', transliteration: 'Kathar Allah kheirak', category: 'Social', level: 5 },
  { id: 'l5-26', english: 'God suffice us', arabic: 'حسبنا الله', transliteration: 'Hasbuna Allah', category: 'Social', level: 5 },
  { id: 'l5-27', english: 'By the bread and salt (Trust)', arabic: 'وحق العيش والملح', transliteration: 'Wa hagg el-aysh wal-mileh', category: 'Idioms', level: 5 },
  { id: 'l5-28', english: 'Don’t make it a big deal', arabic: 'لا تعمل من الحبة قبة', transliteration: 'La ta\'mal min el-habbe qubbe', category: 'Idioms', level: 5 },
  { id: 'l5-29', english: 'Friend in time of need', arabic: 'الصديق وقت الضيق', transliteration: 'As-sadeeg waqt ad-deeg', category: 'Idioms', level: 5 },
  { id: 'l5-30', english: 'Better late than never', arabic: 'أن تصل متأخراً خير من أن لا تصل', transliteration: 'An tasil muta\'akhiran kheir min an la tasil', category: 'Idioms', level: 5 },
  { id: 'l5-31', english: 'I am in a tight spot', arabic: 'أنا بورطة', transliteration: 'Ana bi-warta', category: 'Social', level: 5 },
  { id: 'l5-32', english: 'He is untrustworthy', arabic: 'حية من تحت تبن', transliteration: 'Hayyeh min tahet tiben', category: 'Idioms', level: 5 },
  { id: 'l5-33', english: 'Don’t celebrate too soon', arabic: 'لا تقول فول ليصير بالمكيول', transliteration: 'La tgoul foul layseer bil-makyoul', category: 'Idioms', level: 5 },
  { id: 'l5-34', english: 'Let them fight it out', arabic: 'فخار يكسر بعضه', transliteration: 'Fukhar ykassir ba\'do', category: 'Idioms', level: 5 },
  { id: 'l5-35', english: 'You look pale/scared', arabic: 'وجهك مخطوف', transliteration: 'Wajhak makhtouf', category: 'Social', level: 5 },
  { id: 'l5-36', english: 'He is very stingy', arabic: 'إيده ماسكة', transliteration: 'Ido maskeh', category: 'Idioms', level: 5 },
  { id: 'l5-37', english: 'He is very generous', arabic: 'إيده فرطة', transliteration: 'Ido farta', category: 'Idioms', level: 5 },
  { id: 'l5-38', english: 'Don’t be a nuisance', arabic: 'لا تكون لزقة', transliteration: 'La tkon lazga', category: 'Slang', level: 5 },
  { id: 'l5-39', english: 'I am out of here', arabic: 'أنا فليت', transliteration: 'Ana falleit', category: 'Slang', level: 5 },
  { id: 'l5-40', english: 'Keep it in mind', arabic: 'خليها في بالك', transliteration: 'Khaleeha fi balak', category: 'Social', level: 5 },
  { id: 'l5-41', english: 'Don’t expose us', arabic: 'لا تفضحنا', transliteration: 'La tifdahna', category: 'Social', level: 5 },
  { id: 'l5-42', english: 'You saved me', arabic: 'أنقذتني', transliteration: 'An-qath-tni', category: 'Social', level: 5 },
  { id: 'l5-43', english: 'I am indebted to you', arabic: 'أنا مديون إلك', transliteration: 'Ana madyoun ilak', category: 'Social', level: 5 },
  { id: 'l5-44', english: 'May God keep you', arabic: 'الله يخليك', transliteration: 'Allah yikhalleek', category: 'Greetings', level: 5 },
  // Fixed mapping error: changed duplicate transliteration to category and corrected values.
  { id: 'l5-45', english: 'May God heal you', arabic: 'الله يشفيك', transliteration: 'Allah yishfeek', category: 'Social', level: 5 },
  { id: 'l5-46', english: 'May the baby be blessed', arabic: 'يتربى بعزكم', transliteration: 'Yit-rabba bi-izzkum', category: 'Social', level: 5 },
  { id: 'l5-47', english: 'Deepest condolences', arabic: 'عظم الله أجركم', transliteration: 'Atham Allah ajrakum', category: 'Social', level: 5 },
  { id: 'l5-48', english: 'Condolence Response', arabic: 'شكر الله سعيكم', transliteration: 'Shakar Allah sa\'yakum', category: 'Social', level: 5 },
  { id: 'l5-49', english: 'Wedding blessing', arabic: 'بالرفاه والبنين', transliteration: 'Bil-rafah wal-baneen', category: 'Social', level: 5 },
  { id: 'l5-50', english: 'You made me proud', arabic: 'رفعت راسي', transliteration: 'Rafa\'et rasi', category: 'Social', level: 5 },
  { id: 'l5-51', english: 'Don’t embarrass me', arabic: 'لا تخجلني', transliteration: 'La tikh-jalni', category: 'Social', level: 5 },
  { id: 'l5-52', english: 'He is a smooth talker', arabic: 'لسانه حلو', transliteration: 'Lissano helou', category: 'Slang', level: 5 },
  { id: 'l5-53', english: 'He is a troublemaker', arabic: 'مشكلجي', transliteration: 'Mushkilji', category: 'Slang', level: 5 },
  { id: 'l5-54', english: 'Stop being childish', arabic: 'لا تظلك ولد', transliteration: 'La thallak walad', category: 'Social', level: 5 },
  { id: 'l5-55', english: 'Be a man', arabic: 'خليك زلمة', transliteration: 'Khalleek zalameh', category: 'Social', level: 5 },
  { id: 'l5-56', english: 'You are like gold', arabic: 'إنت ذهب', transliteration: 'Inta thahab', category: 'Social', level: 5 },
  { id: 'l5-57', english: 'Don’t listen to him', arabic: 'لا ترد عليه', transliteration: 'La t-rudd aleih', category: 'Social', level: 5 },
  { id: 'l5-58', english: 'He is showing off', arabic: 'عم بشوف حاله', transliteration: 'Am bishouf halo', category: 'Slang', level: 5 },
  { id: 'l5-59', english: 'The truth of the matter', arabic: 'حقيقة الأمر', transliteration: 'Hageegat al-amer', category: 'Social', level: 5 },
  { id: 'l5-60', english: 'Without exaggeration', arabic: 'بدون مبالغة', transliteration: 'Bidoun mabalagha', category: 'Social', level: 5 },
  { id: 'l5-61', english: '100% sure', arabic: 'متأكد مليون بالمية', transliteration: 'Mit\'akkid malyoun bil-miyyeh', category: 'Social', level: 5 },
  { id: 'l5-62', english: 'Don’t test my patience', arabic: 'لا تمتحن صبري', transliteration: 'La timtahin sabri', category: 'Social', level: 5 },
  { id: 'l5-63', english: 'I have reached my limit', arabic: 'وصلت معي لهون', transliteration: 'Waslat ma\'i la-hon', category: 'Idioms', level: 5 },
  { id: 'l5-64', english: 'I can’t stand it', arabic: 'مش طايق', transliteration: 'Mish tayig', category: 'Social', level: 5 },
  { id: 'l5-65', english: 'Leave it to God', arabic: 'خليها على الله', transliteration: 'Khaleeha ala Allah', category: 'Social', level: 5 },
  { id: 'l5-66', english: 'What a coincidence', arabic: 'يا محاسن الصدف', transliteration: 'Ya mahasin as-sudaf', category: 'Greetings', level: 5 },
  { id: 'l5-67', english: 'It is a small world', arabic: 'الدنيا صغيرة', transliteration: 'Ad-dunya sgheera', category: 'Idioms', level: 5 },
  { id: 'l5-68', english: 'You will see tomorrow', arabic: 'بكره بتشوف', transliteration: 'Bukra bit-shouf', category: 'Social', level: 5 },
  { id: 'l5-69', english: 'Time will show', arabic: 'الأيام بتبين', transliteration: 'Al-ayyam bit-bayyin', category: 'Social', level: 5 },
  { id: 'l5-70', english: 'Apple of my eye', arabic: 'قرة عيني', transliteration: 'Gurr-at aini', category: 'Idioms', level: 5 },
  { id: 'l5-71', english: 'My soul (Affection)', arabic: 'يا روحي', transliteration: 'Ya rouhi', category: 'Social', level: 5 },
  { id: 'l5-72', english: 'My life (Affection)', arabic: 'يا عمري', transliteration: 'Ya omri', category: 'Social', level: 5 },
  { id: 'l5-73', english: 'My heart (Affection)', arabic: 'يا قلبي', transliteration: 'Ya galbi', category: 'Social', level: 5 },
  { id: 'l5-74', english: 'Light of my eyes', arabic: 'يا نور عيوني', transliteration: 'Ya nour oyouni', category: 'Social', level: 5 },
  { id: 'l5-75', english: 'May God protect you', arabic: 'الله يحرسك', transliteration: 'Allah yih-rasak', category: 'Greetings', level: 5 },
  { id: 'l5-76', english: 'If God wills it', arabic: 'إذا الله راد', transliteration: 'Itha Allah rad', category: 'Social', level: 5 },
  { id: 'l5-77', english: 'By God’s grace', arabic: 'بفضل الله', transliteration: 'Bi-fadl Allah', category: 'Social', level: 5 },
  { id: 'l5-78', english: 'Thank God always', arabic: 'الحمد لله على كل حال', transliteration: 'Al-hamdu lillah ala kull hal', category: 'Social', level: 5 },
  { id: 'l5-79', english: 'Safe travels', arabic: 'درب السلامة', transliteration: 'Darb as-salama', category: 'Directions', level: 5 },
  { id: 'l5-80', english: 'Welcome back safely', arabic: 'حمد لله على السلامة', transliteration: 'Hamdillah ala salama', category: 'Greetings', level: 5 },
  { id: 'l5-81', english: 'May God accept it', arabic: 'تقبل الله', transliteration: 'Tagab-bal Allah', category: 'Greetings', level: 5 },
  { id: 'l5-82', english: 'Response: From us and you', arabic: 'منا ومنكم', transliteration: 'Minna wa minkum', category: 'Greetings', level: 5 },
  { id: 'l5-83', english: 'Eat until full', arabic: 'كُل لما تشبع', transliteration: 'Kul lamma tishba\'', category: 'Food', level: 5 },
  { id: 'l5-84', english: 'Drink with pleasure', arabic: 'اشرب بالهنا', transliteration: 'Ishrab bil-hana', category: 'Food', level: 5 },
  { id: 'l5-85', english: 'Health and vitality', arabic: 'بالصحة والعافية', transliteration: 'Bil-sahha wal-afyeh', category: 'Food', level: 5 },
  { id: 'l5-86', english: 'May your house be lively', arabic: 'بيت عامر دايما', transliteration: 'Beit amer dayman', category: 'Social', level: 5 },
  { id: 'l5-87', english: 'House of generosity', arabic: 'بيت كرم', transliteration: 'Beit karam', category: 'Social', level: 5 },
  { id: 'l5-88', english: 'I am your guest/refuge', arabic: 'أنا دخيلك', transliteration: 'Ana dakheelak', category: 'Social', level: 5 },
  { id: 'l5-89', english: 'At your command', arabic: 'لبيك / حاضر', transliteration: 'Labbeik / Hadir', category: 'Social', level: 5 },
  { id: 'l5-90', english: 'On my eyes (Willingly)', arabic: 'على عيني', transliteration: 'Ala aini', category: 'Social', level: 5 },
  { id: 'l5-91', english: 'From my eyes (Gladly)', arabic: 'من عيوني', transliteration: 'Min oyouni', category: 'Social', level: 5 },
  { id: 'l5-92', english: 'Don’t take it personally', arabic: 'لا توخذها شخصي', transliteration: 'La taw-khith-ha shakhsi', category: 'Social', level: 5 },
  { id: 'l5-93', english: 'No hard feelings', arabic: 'بدون زعل', transliteration: 'Bidoun za\'al', category: 'Social', level: 5 },
  { id: 'l5-94', english: 'I am just kidding', arabic: 'بمزح معك', transliteration: 'Bim-zah ma\'ak', category: 'Social', level: 5 },
  { id: 'l5-95', english: 'Take it easy on him', arabic: 'خف عليه', transliteration: 'Khiff aleih', category: 'Social', level: 5 },
  { id: 'l5-96', english: 'Don’t be hard on yourself', arabic: 'لا تقسى على حالك', transliteration: 'La tigsa ala halak', category: 'Social', level: 5 },
  { id: 'l5-97', english: 'Everything will be fine', arabic: 'كل شي راح يصير منيح', transliteration: 'Kull shi rah yiseer mneeha', category: 'Social', level: 5 },
  { id: 'l5-98', english: 'Relief is near', arabic: 'فرج الله قريب', transliteration: 'Faraj Allah gareeb', category: 'Social', level: 5 },
  { id: 'l5-99', english: 'Do not despair', arabic: 'لا تيأس', transliteration: 'La tay\'as', category: 'Social', level: 5 },
  { id: 'l5-100', english: 'Keep your faith strong', arabic: 'خلي إيمانك قوي', transliteration: 'Khalli imanak gawi', category: 'Social', level: 5 },
  { id: 'l5-101', english: 'You are a hero', arabic: 'بطل', transliteration: 'Batal', category: 'Social', level: 5 },
  { id: 'l5-102', english: 'You are a genius', arabic: 'عبقري', transliteration: 'Abgari', category: 'Social', level: 5 },
  { id: 'l5-103', english: 'Don’t be a fool', arabic: 'لا تكون هبيلة', transliteration: 'La tkon habeela', category: 'Slang', level: 5 },
  { id: 'l5-104', english: 'He is a trickster', arabic: 'نصاب', transliteration: 'Nassab', category: 'Slang', level: 5 },
  { id: 'l5-105', english: 'Thief', arabic: 'حرامي', transliteration: 'Harami', category: 'Slang', level: 5 },
  { id: 'l5-106', english: 'Liar', arabic: 'كذاب', transliteration: 'Kathab', category: 'Social', level: 5 },
  { id: 'l5-107', english: 'Coward', arabic: 'جبان', transliteration: 'Jaban', category: 'Social', level: 5 },
  { id: 'l5-108', english: 'Brave', arabic: 'شجاع', transliteration: 'Shuja\'', category: 'Social', level: 5 },
  { id: 'l5-109', english: 'Honest', arabic: 'صادق', transliteration: 'Sadig', category: 'Social', level: 5 },
  { id: 'l5-110', english: 'Loyal', arabic: 'وفي', transliteration: 'Wafi', category: 'Social', level: 5 },
  { id: 'l5-111', english: 'Betrayal', arabic: 'خيانة', transliteration: 'Khiyana', category: 'Social', level: 5 },
  { id: 'l5-112', english: 'Forgiveness', arabic: 'مسامحة', transliteration: 'Masamaha', category: 'Social', level: 5 },
  { id: 'l5-113', english: 'I forgive you', arabic: 'مسامحك', transliteration: 'Masamhak', category: 'Social', level: 5 },
  { id: 'l5-114', english: 'Forget the past', arabic: 'انسى اللي فات', transliteration: 'Insa elly fat', category: 'Social', level: 5 },
  { id: 'l5-115', english: 'A new beginning', arabic: 'بداية جديدة', transliteration: 'Bidaya jdeeda', category: 'Social', level: 5 },
  { id: 'l5-116', english: 'Don’t provoke me', arabic: 'لا تستفزني', transliteration: 'La tistafizni', category: 'Social', level: 5 },
  { id: 'l5-117', english: 'Stay calm', arabic: 'خليك هادي', transliteration: 'Khalleek hadi', category: 'Social', level: 5 },
  { id: 'l5-118', english: 'Wake up (Realize)', arabic: 'اصحى على حالك', transliteration: 'Is-ha ala halak', category: 'Idioms', level: 5 },
  { id: 'l5-119', english: 'In short', arabic: 'باختصار', transliteration: 'Bi-ikhtisar', category: 'Social', level: 5 },
  { id: 'l5-120', english: 'The end', arabic: 'النهاية', transliteration: 'Al-nihaya', category: 'Social', level: 5 },
];