
import { Phrase } from './types';

export const level1: Phrase[] = [
  { id: 'l1-1', english: 'Hello', arabic: 'مرحبا', transliteration: 'Marhaba', category: 'Greetings', level: 1 },
  { id: 'l1-2', english: 'Welcome', arabic: 'أهلا وسهلا', transliteration: 'Ahlan wa Sahlan', category: 'Greetings', level: 1 },
  { id: 'l1-3', english: 'How are you?', arabic: 'كيفك؟', transliteration: 'Keifak?', category: 'Greetings', level: 1 },
  { id: 'l1-4', english: 'Good / Fine', arabic: 'تمام', transliteration: 'Tamam', category: 'Greetings', level: 1 },
  { id: 'l1-5', english: 'Good morning', arabic: 'صباح الخير', transliteration: 'Sabah el-kheir', category: 'Greetings', level: 1 },
  { id: 'l1-6', english: 'Good evening', arabic: 'مساء الخير', transliteration: 'Masa el-kheir', category: 'Greetings', level: 1 },
  { id: 'l1-7', english: 'Thank you', arabic: 'شكراً', transliteration: 'Shukran', category: 'Greetings', level: 1 },
  { id: 'l1-8', english: 'Yes', arabic: 'آه / نعم', transliteration: 'Ah / Naam', category: 'Social', level: 1 },
  { id: 'l1-9', english: 'No', arabic: 'لأ', transliteration: 'La’', category: 'Social', level: 1 },
  { id: 'l1-10', english: 'Please', arabic: 'لو سمحت', transliteration: 'Law samahet', category: 'Social', level: 1 },
  { id: 'l1-11', english: 'Excuse me', arabic: 'عن اذنك', transliteration: 'An iznak', category: 'Social', level: 1 },
  { id: 'l1-12', english: 'Sorry', arabic: 'آسف', transliteration: 'Asef', category: 'Social', level: 1 },
  { id: 'l1-13', english: 'How much?', arabic: 'قديه؟', transliteration: 'Gaddieh?', category: 'Market', level: 1 },
  { id: 'l1-14', english: 'Where?', arabic: 'وين؟', transliteration: 'Wein?', category: 'Directions', level: 1 },
  { id: 'l1-15', english: 'When?', arabic: 'إمتى؟', transliteration: 'Emta?', category: 'Social', level: 1 },
  { id: 'l1-16', english: 'Who?', arabic: 'مين؟', transliteration: 'Meen?', category: 'Social', level: 1 },
  { id: 'l1-17', english: 'What?', arabic: 'شو؟', transliteration: 'Shu?', category: 'Social', level: 1 },
  { id: 'l1-18', english: 'Why?', arabic: 'ليش؟', transliteration: 'Leish?', category: 'Social', level: 1 },
  { id: 'l1-19', english: 'I am...', arabic: 'أنا...', transliteration: 'Ana...', category: 'Social', level: 1 },
  { id: 'l1-20', english: 'Goodbye', arabic: 'مع السلامة', transliteration: 'Ma’as-salama', category: 'Greetings', level: 1 },
  { id: 'l1-21', english: 'God bless you', arabic: 'يعطيك العافية', transliteration: 'Ya’teek el-afye', category: 'Greetings', level: 1 },
  { id: 'l1-22', english: 'Nice to meet you', arabic: 'فرصة سعيدة', transliteration: 'Fursa sa’eeda', category: 'Greetings', level: 1 },
  { id: 'l1-23', english: 'My name is...', arabic: 'اسمي...', transliteration: 'Ismi...', category: 'Social', level: 1 },
  { id: 'l1-24', english: 'I live in...', arabic: 'ساكن بـ...', transliteration: 'Saken bi...', category: 'Social', level: 1 },
  { id: 'l1-25', english: 'What is your name?', arabic: 'شو اسمك؟', transliteration: 'Shu ismak?', category: 'Social', level: 1 },
  { id: 'l1-26', english: 'I am from...', arabic: 'أنا من...', transliteration: 'Ana min...', category: 'Social', level: 1 },
  { id: 'l1-27', english: 'I am American', arabic: 'أنا أمريكي', transliteration: 'Ana Amreeki', category: 'Social', level: 1 },
  { id: 'l1-28', english: 'I speak English', arabic: 'بحكي إنجليزي', transliteration: 'Bahki inglizi', category: 'Social', level: 1 },
  { id: 'l1-29', english: 'A little', arabic: 'شوي', transliteration: 'Shway', category: 'Social', level: 1 },
  { id: 'l1-30', english: 'I don’t speak Arabic', arabic: 'ما بحكي عربي', transliteration: 'Ma bahki arabi', category: 'Social', level: 1 },
  { id: 'l1-31', english: 'Wait', arabic: 'استنى', transliteration: 'Istanna', category: 'Social', level: 1 },
  { id: 'l1-32', english: 'Look', arabic: 'شوف', transliteration: 'Shouf', category: 'Social', level: 1 },
  { id: 'l1-33', english: 'Listen', arabic: 'اسمع', transliteration: 'Isma’', category: 'Social', level: 1 },
  { id: 'l1-34', english: 'Understand?', arabic: 'فاهم؟', transliteration: 'Fahem?', category: 'Social', level: 1 },
  { id: 'l1-35', english: 'I don’t understand', arabic: 'مش فاهم', transliteration: 'Mish fahem', category: 'Social', level: 1 },
  { id: 'l1-36', english: 'Repeat', arabic: 'عيد', transliteration: 'Eed', category: 'Social', level: 1 },
  { id: 'l1-37', english: 'Slowly', arabic: 'شوي شوي', transliteration: 'Shway shway', category: 'Social', level: 1 },
  { id: 'l1-38', english: 'Big', arabic: 'كبير', transliteration: 'Kbeer', category: 'Social', level: 1 },
  { id: 'l1-39', english: 'Small', arabic: 'صغير', transliteration: 'Sgheer', category: 'Social', level: 1 },
  { id: 'l1-40', english: 'Today', arabic: 'اليوم', transliteration: 'El-youm', category: 'Social', level: 1 },
  { id: 'l1-41', english: 'Tomorrow', arabic: 'بكرة', transliteration: 'Bukra', category: 'Social', level: 1 },
  { id: 'l1-42', english: 'Yesterday', arabic: 'مبارح', transliteration: 'Mbareh', category: 'Social', level: 1 },
  { id: 'l1-43', english: 'Now', arabic: 'هسا / هلق', transliteration: 'Hassa / Hallag', category: 'Social', level: 1 },
  { id: 'l1-44', english: 'Later', arabic: 'بعدين', transliteration: 'Ba’dein', category: 'Social', level: 1 },
  { id: 'l1-45', english: 'Always', arabic: 'دايما', transliteration: 'Dayman', category: 'Social', level: 1 },
  { id: 'l1-46', english: 'Never', arabic: 'أبدا', transliteration: 'Abadan', category: 'Social', level: 1 },
  { id: 'l1-47', english: 'Maybe', arabic: 'ممكن / بجوز', transliteration: 'Mumkin / Bijouz', category: 'Social', level: 1 },
  { id: 'l1-48', english: 'Problem', arabic: 'مشكلة', transliteration: 'Mushkila', category: 'Social', level: 1 },
  { id: 'l1-49', english: 'No problem', arabic: 'مش مشكلة', transliteration: 'Mish mushkila', category: 'Social', level: 1 },
  { id: 'l1-50', english: 'Okay', arabic: 'ماشي', transliteration: 'Mashi', category: 'Social', level: 1 },
  { id: 'l1-51', english: "Don't worry", arabic: 'ولا يهمك', transliteration: 'Wala yhemmak', category: 'Social', level: 1 },
  { id: 'l1-52', english: 'Of course', arabic: 'طبعاً', transliteration: 'Tab\'an', category: 'Social', level: 1 },
  { id: 'l1-53', english: 'Seriously?', arabic: 'جد؟', transliteration: 'Jad?', category: 'Social', level: 1 },
  { id: 'l1-54', english: 'Correct', arabic: 'صح', transliteration: 'Sah', category: 'Social', level: 1 },
  { id: 'l1-55', english: 'Wrong', arabic: 'غلط', transliteration: 'Ghalat', category: 'Social', level: 1 },
  { id: 'l1-56', english: 'Ready?', arabic: 'جاهز؟', transliteration: 'Jahez?', category: 'Social', level: 1 },
  { id: 'l1-57', english: 'Enough', arabic: 'خلص', transliteration: 'Khalas', category: 'Social', level: 1 },
  { id: 'l1-58', english: 'More', arabic: 'كمان', transliteration: 'Kaman', category: 'Social', level: 1 },
  { id: 'l1-59', english: 'Only', arabic: 'بس', transliteration: 'Bas', category: 'Social', level: 1 },
  { id: 'l1-60', english: 'Everything', arabic: 'كل شي', transliteration: 'Kull shi', category: 'Social', level: 1 },
  { id: 'l1-61', english: 'Me too', arabic: 'أنا كمان', transliteration: 'Ana kaman', category: 'Social', level: 1 },
  { id: 'l1-62', english: 'For me', arabic: 'إلي', transliteration: 'Ili', category: 'Social', level: 1 },
  { id: 'l1-63', english: 'For you', arabic: 'إلك', transliteration: 'Ilak', category: 'Social', level: 1 },
  { id: 'l1-64', english: 'With you', arabic: 'معك', transliteration: 'Ma\'ak', category: 'Social', level: 1 },
  { id: 'l1-65', english: 'Like this', arabic: 'هيك', transliteration: 'Heik', category: 'Social', level: 1 },
  { id: 'l1-66', english: 'Way / Road', arabic: 'طريق', transliteration: 'Tareeg', category: 'Directions', level: 1 },
  { id: 'l1-67', english: 'Outside', arabic: 'بره', transliteration: 'Barra', category: 'Directions', level: 1 },
  { id: 'l1-68', english: 'Inside', arabic: 'جوه', transliteration: 'Jouwa', category: 'Directions', level: 1 },
  { id: 'l1-69', english: 'Up', arabic: 'فوق', transliteration: 'Foug', category: 'Directions', level: 1 },
  { id: 'l1-70', english: 'Down', arabic: 'تحت', transliteration: 'Tahet', category: 'Directions', level: 1 },
  { id: 'l1-71', english: 'Early', arabic: 'بكير', transliteration: 'Bakkir', category: 'Social', level: 1 },
  { id: 'l1-72', english: 'Soon', arabic: 'قريباً', transliteration: 'Gareeban', category: 'Social', level: 1 },
  { id: 'l1-73', english: 'Slow', arabic: 'بطيء', transliteration: 'Batee\'', category: 'Social', level: 1 },
  { id: 'l1-74', english: 'Fast', arabic: 'سريع', transliteration: 'Saree\'', category: 'Social', level: 1 },
  { id: 'l1-75', english: 'Strong', arabic: 'قوي', transliteration: 'Gawi', category: 'Social', level: 1 },
  { id: 'l1-76', english: 'Weak', arabic: 'ضعيف', transliteration: 'Da\'eef', category: 'Social', level: 1 },
  { id: 'l1-77', english: 'New', arabic: 'جديد', transliteration: 'Jdeed', category: 'Social', level: 1 },
  { id: 'l1-78', english: 'Old', arabic: 'قديم', transliteration: 'Gadeem', category: 'Social', level: 1 },
  { id: 'l1-79', english: 'Clean', arabic: 'نظيف', transliteration: 'Ntheef', category: 'Social', level: 1 },
  { id: 'l1-80', english: 'Dirty', arabic: 'وسخ', transliteration: 'Wasekh', category: 'Social', level: 1 },
  { id: 'l1-81', english: 'Easy', arabic: 'سهل', transliteration: 'Sahel', category: 'Social', level: 1 },
  { id: 'l1-82', english: 'Difficult', arabic: 'صعب', transliteration: 'Sa\'eb', category: 'Social', level: 1 },
  { id: 'l1-83', english: 'Probably', arabic: 'بجوز', transliteration: 'Bijouz', category: 'Social', level: 1 },
  { id: 'l1-84', english: 'Impossible', arabic: 'مستحيل', transliteration: 'Mustaheel', category: 'Social', level: 1 },
  { id: 'l1-85', english: 'My friend', arabic: 'صاحبي', transliteration: 'Sahbi', category: 'Social', level: 1 },
  { id: 'l1-86', english: 'Habibi', arabic: 'حبيبي', transliteration: 'Habibi', category: 'Social', level: 1 },
  { id: 'l1-87', english: 'Good night', arabic: 'تصبح على خير', transliteration: 'Tisbah ala kheir', category: 'Greetings', level: 1 },
  { id: 'l1-88', english: 'Congratulations', arabic: 'مبروك', transliteration: 'Mabrouk', category: 'Social', level: 1 },
  { id: 'l1-89', english: 'Really?', arabic: 'عنجد؟', transliteration: 'Anjad?', category: 'Social', level: 1 },
  { id: 'l1-90', english: "What's this?", arabic: 'شو هذا؟', transliteration: 'Shu hada?', category: 'Social', level: 1 },
  { id: 'l1-91', english: "Who's this?", arabic: 'مين هذا؟', transliteration: 'Meen hada?', category: 'Social', level: 1 },
  { id: 'l1-92', english: 'Give me', arabic: 'أعطيني', transliteration: 'A\'teeni', category: 'Market', level: 1 },
  { id: 'l1-93', english: 'Show me', arabic: 'فرجيني', transliteration: 'Farjeeni', category: 'Market', level: 1 },
  { id: 'l1-94', english: 'Take this', arabic: 'خذ هذا', transliteration: 'Khod hada', category: 'Social', level: 1 },
  { id: 'l1-95', english: 'Call me', arabic: 'رن علي', transliteration: 'Irn ali', category: 'Social', level: 1 },
  { id: 'l1-96', english: "I'm lost", arabic: 'أنا ضايع', transliteration: 'Ana daye\'', category: 'Social', level: 1 },
  { id: 'l1-97', english: 'Happy', arabic: 'مبسوط', transliteration: 'Mabsoot', category: 'Social', level: 1 },
  { id: 'l1-98', english: 'Sad', arabic: 'حزين', transliteration: 'Hazeen', category: 'Social', level: 1 },
  { id: 'l1-99', english: 'Angry', arabic: 'زعلان', transliteration: 'Za\'lan', category: 'Social', level: 1 },
  { id: 'l1-100', english: 'Nice', arabic: 'لطيف', transliteration: 'Lateef', category: 'Social', level: 1 },
  { id: 'l1-101', english: 'Smart', arabic: 'ذكي', transliteration: 'Dhaki', category: 'Social', level: 1 },
  { id: 'l1-102', english: 'Funny', arabic: 'بضحك', transliteration: 'Bi-dahhik', category: 'Social', level: 1 },
  { id: 'l1-103', english: 'See you', arabic: 'بشوفك', transliteration: 'Bashoufak', category: 'Greetings', level: 1 },
  { id: 'l1-104', english: 'Late', arabic: 'متأخر', transliteration: 'Muta\'akhir', category: 'Social', level: 1 },
  { id: 'l1-105', english: 'Go', arabic: 'روح', transliteration: 'Rouh', category: 'Directions', level: 1 },
  { id: 'l1-106', english: 'Come here', arabic: 'تعال هون', transliteration: 'Ta\'al hon', category: 'Directions', level: 1 },
  { id: 'l1-107', english: 'Sit down', arabic: 'اقعد', transliteration: 'Ig\'od', category: 'Social', level: 1 },
  { id: 'l1-108', english: 'Stand up', arabic: 'قوم', transliteration: 'Goum', category: 'Social', level: 1 },
  { id: 'l1-109', english: 'Speak', arabic: 'احكي', transliteration: 'Ihki', category: 'Social', level: 1 },
  { id: 'l1-110', english: 'Listen to me', arabic: 'اسمعني', transliteration: 'Isma\'ni', category: 'Social', level: 1 },
  { id: 'l1-111', english: 'Open it', arabic: 'افتحه', transliteration: 'Iftaho', category: 'Social', level: 1 },
  { id: 'l1-112', english: 'Close it', arabic: 'سكره', transliteration: 'Sakkro', category: 'Social', level: 1 },
  { id: 'l1-113', english: 'Give it back', arabic: 'رجعه', transliteration: 'Rajje\'o', category: 'Social', level: 1 },
  { id: 'l1-114', english: "I'm coming", arabic: 'أنا جاي', transliteration: 'Ana jay', category: 'Social', level: 1 },
  { id: 'l1-115', english: 'Tonight', arabic: 'الليلة', transliteration: 'El-leileh', category: 'Social', level: 1 },
  { id: 'l1-116', english: 'Never mind', arabic: 'مش مهم', transliteration: 'Mish muhem', category: 'Social', level: 1 },
  { id: 'l1-117', english: 'Sometimes', arabic: 'مرات', transliteration: 'Marat', category: 'Social', level: 1 },
  { id: 'l1-118', english: 'I think', arabic: 'بظن', transliteration: 'Bazun', category: 'Social', level: 1 },
  { id: 'l1-119', english: 'Beautiful', arabic: 'حلو', transliteration: 'Helou', category: 'Social', level: 1 },
  { id: 'l1-120', english: 'Excellent', arabic: 'ممتاز', transliteration: 'Mumtaz', category: 'Social', level: 1 },
];
