
import { Phrase } from './types';

export const level3: Phrase[] = [
  { id: 'l3-1', english: 'What’s up?', arabic: 'شو الأخبار؟', transliteration: 'Shu al-akhbar?', category: 'Social', level: 3 },
  { id: 'l3-2', english: 'Everything is fine', arabic: 'كل شي تمام', transliteration: 'Kull shi tamam', category: 'Social', level: 3 },
  { id: 'l3-3', english: 'How is work?', arabic: 'كيف الشغل؟', transliteration: 'Keif esh-shughul?', category: 'Social', level: 3 },
  { id: 'l3-4', english: 'Give me a discount', arabic: 'راعيني بالسعر', transliteration: 'Ra’eeni bis-si’er', category: 'Market', level: 3 },
  { id: 'l3-5', english: 'Too much', arabic: 'كتير هيك', transliteration: 'Kteer heik', category: 'Market', level: 3 },
  { id: 'l3-6', english: 'The last price?', arabic: 'آخر كلام؟', transliteration: 'Akher kalam?', category: 'Market', level: 3 },
  { id: 'l3-7', english: 'I will take it', arabic: 'خلص باخذه', transliteration: 'Khalas bakhtho', category: 'Market', level: 3 },
  { id: 'l3-8', english: 'Bag', arabic: 'كيس', transliteration: 'Keis', category: 'Market', level: 3 },
  { id: 'l3-9', english: 'Are you sure?', arabic: 'متأكد؟', transliteration: 'Mit’akkid?', category: 'Social', level: 3 },
  { id: 'l3-10', english: 'Of course', arabic: 'طبعاً', transliteration: 'Tab’an', category: 'Social', level: 3 },
  { id: 'l3-11', english: 'I think so', arabic: 'بظن هيك', transliteration: 'Bazun heik', category: 'Social', level: 3 },
  { id: 'l3-12', english: 'It depends', arabic: 'حسب', transliteration: 'Hasab', category: 'Social', level: 3 },
  { id: 'l3-13', english: 'Really?', arabic: 'عنجد؟', transliteration: 'Anjad?', category: 'Social', level: 3 },
  { id: 'l3-14', english: 'I forgot', arabic: 'نسيت', transliteration: 'Niseit', category: 'Social', level: 3 },
  { id: 'l3-15', english: 'I remembered', arabic: 'تذكرت', transliteration: 'Tizakkaret', category: 'Social', level: 3 },
  { id: 'l3-16', english: 'I am busy', arabic: 'مشغول', transliteration: 'Mashghoul', category: 'Social', level: 3 },
  { id: 'l3-17', english: 'I am free', arabic: 'فاضي', transliteration: 'Fadi', category: 'Social', level: 3 },
  { id: 'l3-18', english: 'What happened?', arabic: 'شو صار؟', transliteration: 'Shu sar?', category: 'Social', level: 3 },
  { id: 'l3-19', english: 'Nothing happened', arabic: 'ما صار شي', transliteration: 'Ma sar shi', category: 'Social', level: 3 },
  { id: 'l3-20', english: 'Wait a second', arabic: 'ثانية وحدة', transliteration: 'Thanya wahdeh', category: 'Social', level: 3 },
  { id: 'l3-21', english: "I'm looking for...", arabic: 'بدوّر على...', transliteration: 'Badawwer ala...', category: 'Social', level: 3 },
  { id: 'l3-22', english: 'Do you have change for 10?', arabic: 'معك فراطة عشرة؟', transliteration: 'Ma\'ak fratat ashra?', category: 'Market', level: 3 },
  { id: 'l3-23', english: 'Where is the nearest ATM?', arabic: 'وين أقرب صراف؟', transliteration: 'Wein agrab sarraf?', category: 'Directions', level: 3 },
  { id: 'l3-24', english: "It's not working", arabic: 'مش شغال', transliteration: 'Mish shagghal', category: 'Social', level: 3 },
  { id: 'l3-25', english: 'I have a question', arabic: 'عندي سؤال', transliteration: 'Andi su\'al', category: 'Social', level: 3 },
  { id: 'l3-26', english: 'I need to go', arabic: 'لازم أروح', transliteration: 'Lazim arouh', category: 'Social', level: 3 },
  { id: 'l3-27', english: 'Are you ready?', arabic: 'جاهز؟', transliteration: 'Jahez?', category: 'Social', level: 3 },
  { id: 'l3-28', english: 'I am coming now', arabic: 'أنا جاي هسا', transliteration: 'Ana jay hassa', category: 'Social', level: 3 },
  { id: 'l3-29', english: "I'll be late", arabic: 'راح أتأخر', transliteration: 'Rah ata\'akhar', category: 'Social', level: 3 },
  { id: 'l3-30', english: 'Where should we meet?', arabic: 'وين نلتقي؟', transliteration: 'Wein niltagi?', category: 'Directions', level: 3 },
  { id: 'l3-31', english: 'Wait for me outside', arabic: 'استناني بره', transliteration: 'Istannani barra', category: 'Directions', level: 3 },
  { id: 'l3-32', english: 'Whose is this?', arabic: 'لمين هذا؟', transliteration: 'Lameen hada?', category: 'Social', level: 3 },
  { id: 'l3-33', english: 'I don’t care', arabic: 'مش فارقة معي', transliteration: 'Mish farga ma\'i', category: 'Social', level: 3 },
  { id: 'l3-34', english: 'Tell me the truth', arabic: 'احكيلي الصراحة', transliteration: 'Ihkili as-saraha', category: 'Social', level: 3 },
  { id: 'l3-35', english: 'I am bored', arabic: 'زهقان', transliteration: 'Zahgan', category: 'Social', level: 3 },
  { id: 'l3-36', english: 'You are right', arabic: 'معك حق', transliteration: 'Ma\'ak hagg', category: 'Social', level: 3 },
  { id: 'l3-37', english: 'I am not sure', arabic: 'مش متأكد', transliteration: 'Mish mit\'akkid', category: 'Social', level: 3 },
  { id: 'l3-38', english: 'Let’s try it', arabic: 'خلينا نجربه', transliteration: 'Khaleena njarrbo', category: 'Social', level: 3 },
  { id: 'l3-39', english: 'Is this available?', arabic: 'هذا موجود؟', transliteration: 'Hada mowjood?', category: 'Market', level: 3 },
  { id: 'l3-40', english: 'Where can I find...?', arabic: 'وين بلاقي...؟', transliteration: 'Wein balagi...?', category: 'Market', level: 3 },
  { id: 'l3-41', english: 'I want to ask you something', arabic: 'بدي أسألك شي', transliteration: 'Biddi as\'alak shi', category: 'Social', level: 3 },
  { id: 'l3-42', english: 'It was nice', arabic: 'كان حلو', transliteration: 'Kan helou', category: 'Social', level: 3 },
  { id: 'l3-43', english: 'Come with me', arabic: 'تعال معي', transliteration: 'Ta\'al ma\'i', category: 'Social', level: 3 },
  { id: 'l3-44', english: 'I missed you', arabic: 'اشتقتلك', transliteration: 'Ishtagtilak', category: 'Social', level: 3 },
  { id: 'l3-45', english: 'What do you recommend?', arabic: 'شو بتنصحني؟', transliteration: 'Shu bit-nasahni?', category: 'Food', level: 3 },
  { id: 'l3-46', english: 'I am confused', arabic: 'أنا محتار', transliteration: 'Ana muhtar', category: 'Social', level: 3 },
  { id: 'l3-47', english: 'Don’t be angry', arabic: 'لا تزعل', transliteration: 'La tiz\'al', category: 'Social', level: 3 },
  { id: 'l3-48', english: 'Help me with this', arabic: 'ساعدني بهي', transliteration: 'Sa\'idni bi-hay', category: 'Social', level: 3 },
  { id: 'l3-49', english: 'It’s very easy', arabic: 'كتير سهل', transliteration: 'Kteer sahel', category: 'Social', level: 3 },
  { id: 'l3-50', english: 'It’s impossible', arabic: 'مستحيل', transliteration: 'Mustaheel', category: 'Social', level: 3 },
  { id: 'l3-51', english: 'I am waiting for you', arabic: 'أنا بستنى فيك', transliteration: 'Ana bastanna feek', category: 'Social', level: 3 },
  { id: 'l3-52', english: 'Where are we going?', arabic: 'وين رايحين؟', transliteration: 'Wein rayheen?', category: 'Directions', level: 3 },
  { id: 'l3-53', english: 'I have no idea', arabic: 'ما عندي فكرة', transliteration: 'Ma andi fikra', category: 'Social', level: 3 },
  { id: 'l3-54', english: 'Don’t worry about it', arabic: 'لا تهتم', transliteration: 'La tihtam', category: 'Social', level: 3 },
  { id: 'l3-55', english: 'Is there a discount?', arabic: 'في خصم؟', transliteration: 'Fi khasm?', category: 'Market', level: 3 },
  { id: 'l3-56', english: 'It’s cheap here', arabic: 'رخيص هون', transliteration: 'Rakhees hon', category: 'Market', level: 3 },
  { id: 'l3-57', english: 'The quality is good', arabic: 'الجودة منيحة', transliteration: 'Al-jawda mneeha', category: 'Market', level: 3 },
  { id: 'l3-58', english: 'I need a receipt', arabic: 'بدي وصل / فاتورة', transliteration: 'Biddi wasel / fatoura', category: 'Market', level: 3 },
  { id: 'l3-59', english: 'Can I pay by card?', arabic: 'بقدر أدفع بالبطاقة؟', transliteration: 'Bigdar adfa\' bil-bitaga?', category: 'Market', level: 3 },
  { id: 'l3-60', english: 'Where is the manager?', arabic: 'وين المدير؟', transliteration: 'Wein al-mudeer?', category: 'Social', level: 3 },
  { id: 'l3-61', english: 'I have an appointment', arabic: 'عندي موعد', transliteration: 'Andi mow\'ed', category: 'Social', level: 3 },
  { id: 'l3-62', english: 'I will call you back', arabic: 'برجع برن عليك', transliteration: 'Barja\' barinn aleik', category: 'Social', level: 3 },
  { id: 'l3-63', english: 'Send me the location', arabic: 'ابعثلي اللوكيشن', transliteration: 'Iba\'thli al-location', category: 'Directions', level: 3 },
  { id: 'l3-64', english: 'The battery is dead', arabic: 'البطارية خلصت', transliteration: 'Al-battariyeh khallast', category: 'Social', level: 3 },
  { id: 'l3-65', english: 'The signal is weak', arabic: 'الشبكة ضعيفة', transliteration: 'Ash-shabaka da\'eefa', category: 'Social', level: 3 },
  { id: 'l3-66', english: 'I am at home', arabic: 'أنا بالبيت', transliteration: 'Ana bil-beit', category: 'Directions', level: 3 },
  { id: 'l3-67', english: 'I am at work', arabic: 'أنا بالشغل', transliteration: 'Ana bish-shughul', category: 'Social', level: 3 },
  { id: 'l3-68', english: 'I am on the way', arabic: 'أنا بالطريق', transliteration: 'Ana bit-tareeg', category: 'Directions', level: 3 },
  { id: 'l3-69', english: 'Traffic is bad', arabic: 'الأزمة قوية', transliteration: 'Al-azmeh gawyeh', category: 'Directions', level: 3 },
  { id: 'l3-70', english: 'I will be there in 5 mins', arabic: 'بكون هناك كمان ٥ دقايق', transliteration: 'Bakoun hunak kaman khams dagayeg', category: 'Social', level: 3 },
  { id: 'l3-71', english: 'Is the food ready?', arabic: 'الأكل جاهز؟', transliteration: 'Al-akel jahez?', category: 'Food', level: 3 },
  { id: 'l3-72', english: 'The food is cold', arabic: 'الأكل بارد', transliteration: 'Al-akel bared', category: 'Food', level: 3 },
  { id: 'l3-73', english: 'Warm it up, please', arabic: 'سخنه لو سمحت', transliteration: 'Sakhno law samahet', category: 'Food', level: 3 },
  { id: 'l3-74', english: 'I want a table for two', arabic: 'بدي طاولة لشخصين', transliteration: 'Biddi tawla la-shakhsein', category: 'Food', level: 3 },
  { id: 'l3-75', english: 'Inside or outside?', arabic: 'جوه ولا بره؟', transliteration: 'Jouwa wala barra?', category: 'Food', level: 3 },
  { id: 'l3-76', english: 'Enjoy your meal', arabic: 'صحتين', transliteration: 'Sahtein', category: 'Food', level: 3 },
  { id: 'l3-77', english: 'To your heart (Response)', arabic: 'على قلبك', transliteration: 'Ala galbak', category: 'Food', level: 3 },
  { id: 'l3-78', english: 'I am full', arabic: 'شبعت', transliteration: 'Shiba\'et', category: 'Food', level: 3 },
  { id: 'l3-79', english: 'I am still hungry', arabic: 'لسا جوعان', transliteration: 'Lissa jow\'an', category: 'Food', level: 3 },
  { id: 'l3-80', english: 'The service is slow', arabic: 'الخدمة بطيئة', transliteration: 'Al-khidmeh batee\'a', category: 'Food', level: 3 },
  { id: 'l3-81', english: 'Do you need anything?', arabic: 'بدك شي؟', transliteration: 'Biddak shi?', category: 'Social', level: 3 },
  { id: 'l3-82', english: 'No, thank you', arabic: 'سلامتك', transliteration: 'Salamtak', category: 'Social', level: 3 },
  { id: 'l3-83', english: 'God bless you', arabic: 'الله يسلمك', transliteration: 'Allah yisallmak', category: 'Social', level: 3 },
  { id: 'l3-84', english: 'Take care of yourself', arabic: 'دير بالك على حالك', transliteration: 'Deer balak ala halak', category: 'Social', level: 3 },
  { id: 'l3-85', english: 'I will see you later', arabic: 'بشوفك بعدين', transliteration: 'Bashoufak ba\'dein', category: 'Social', level: 3 },
  { id: 'l3-86', english: 'Keep in touch', arabic: 'خلينا على تواصل', transliteration: 'Khaleena ala tawasul', category: 'Social', level: 3 },
  { id: 'l3-87', english: 'I am happy to see you', arabic: 'مبسوط إني شفتك', transliteration: 'Mabsoot inni shoftak', category: 'Social', level: 3 },
  { id: 'l3-88', english: 'What’s your opinion?', arabic: 'شو رأيك؟', transliteration: 'Shu ra\'yak?', category: 'Social', level: 3 },
  { id: 'l3-89', english: 'I agree with you', arabic: 'بوافقك الرأي', transliteration: 'Bawafgak ar-ra\'i', category: 'Social', level: 3 },
  { id: 'l3-90', english: 'I disagree', arabic: 'ما بظن هيك', transliteration: 'Ma bazun heik', category: 'Social', level: 3 },
  { id: 'l3-91', english: 'Let’s change the subject', arabic: 'خلينا نغير الموضوع', transliteration: 'Khaleena nghayyer al-mawdo\'', category: 'Social', level: 3 },
  { id: 'l3-92', english: 'It’s a secret', arabic: 'هذا سر', transliteration: 'Hada sirr', category: 'Social', level: 3 },
  { id: 'l3-93', english: 'Don’t tell anyone', arabic: 'لا تحكي لحدا', transliteration: 'La tihki la-hada', category: 'Social', level: 3 },
  { id: 'l3-94', english: 'I trust you', arabic: 'بثق فيك', transliteration: 'Bathig feek', category: 'Social', level: 3 },
  { id: 'l3-95', english: 'I am proud of you', arabic: 'فخور فيك', transliteration: 'Fakhour feek', category: 'Social', level: 3 },
  { id: 'l3-96', english: 'You did a good job', arabic: 'عملت شغل منيح', transliteration: 'Amalt shughul mneeha', category: 'Social', level: 3 },
  { id: 'l3-97', english: 'Don’t give up', arabic: 'لا تستسلم', transliteration: 'La tistaslim', category: 'Social', level: 3 },
  { id: 'l3-98', english: 'Keep going', arabic: 'استمر', transliteration: 'Istamirr', category: 'Social', level: 3 },
  { id: 'l3-99', english: 'Good luck', arabic: 'بالتوفيق', transliteration: 'Bil-tawfeeq', category: 'Social', level: 3 },
  { id: 'l3-100', english: 'Happy Birthday', arabic: 'كل عام وإنت بخير', transliteration: 'Kull am wa inta b-kheir', category: 'Social', level: 3 },
  { id: 'l3-101', english: 'I am really tired', arabic: 'أنا ميت تعب', transliteration: 'Ana mayyet ta\'ab', category: 'Slang', level: 3 },
  { id: 'l3-102', english: "It's nothing", arabic: 'بسيطة', transliteration: 'Baseeta', category: 'Social', level: 3 },
  { id: 'l3-103', english: 'Exactly!', arabic: 'بالضبط!', transliteration: 'Biddabt!', category: 'Social', level: 3 },
  { id: 'l3-104', english: 'Just a moment', arabic: 'لحظة شوي', transliteration: 'Lahtha shway', category: 'Social', level: 3 },
  { id: 'l3-105', english: 'Believe me', arabic: 'صدقني', transliteration: 'Saddigni', category: 'Social', level: 3 },
  { id: 'l3-106', english: 'I swear', arabic: 'والله', transliteration: 'Wallah', category: 'Social', level: 3 },
  { id: 'l3-107', english: 'No way', arabic: 'مش معقول', transliteration: 'Mish ma\'goul', category: 'Social', level: 3 },
  { id: 'l3-108', english: 'Are you kidding?', arabic: 'بتمزح؟', transliteration: 'Bitimzah?', category: 'Social', level: 3 },
  { id: 'l3-109', english: 'I am serious', arabic: 'بحكي جد', transliteration: 'Bahki jad', category: 'Social', level: 3 },
  { id: 'l3-110', english: 'Forget it', arabic: 'انسى الموضوع', transliteration: 'Insa al-mawdo\'', category: 'Social', level: 3 },
  { id: 'l3-111', english: 'Whatever you want', arabic: 'اللي بدك اياه', transliteration: 'Illi biddak iyyah', category: 'Social', level: 3 },
  { id: 'l3-112', english: "It's your choice", arabic: 'الخيار إلك', transliteration: 'Al-khiyar ilak', category: 'Social', level: 3 },
  { id: 'l3-113', english: "Don't be shy", arabic: 'لا تستحي', transliteration: 'La tistahi', category: 'Social', level: 3 },
  { id: 'l3-114', english: 'Be patient', arabic: 'طوّل بالك', transliteration: 'Tawwil balak', category: 'Social', level: 3 },
  { id: 'l3-115', english: 'Go ahead', arabic: 'تفضل', transliteration: 'Tfaddal', category: 'Social', level: 3 },
  { id: 'l3-116', english: 'What else?', arabic: 'شو كمان؟', transliteration: 'Shu kaman?', category: 'Social', level: 3 },
  { id: 'l3-117', english: 'Nothing else', arabic: 'بس هيك', transliteration: 'Bas heik', category: 'Social', level: 3 },
  { id: 'l3-118', english: "That's it", arabic: 'خلصنا', transliteration: 'Khallasna', category: 'Social', level: 3 },
  { id: 'l3-119', english: 'Excellent!', arabic: 'ممتاز!', transliteration: 'Mumtaz!', category: 'Social', level: 3 },
  { id: 'l3-120', english: 'Great!', arabic: 'عظيم!', transliteration: 'Atheem!', category: 'Social', level: 3 },
];
